module.exports = {
  Align: require('./components/align'),
  Button: require('./components/button'),
  ButtonContainer: require('./components/button-container'),
  Card: require('./components/card'),
  Checkbox: require('./components/checkbox'),
  CheckboxGroup: require('./components/checkbox-group'),
  ContactCard: require('./components/contact-card'),
  Dropzone: require('./components/dropzone'),
  Icon: require('./components/icon'),
  Input: require('./components/input'),
  InputField: require('./components/input-field'),
  Link: require('./components/link'),
  Loader: require('./components/loader'),
  Modal: require('./components/modal'),
  Pill: require('./components/pill'),
  PillGroup: require('./components/pill-group'),
  RadioButton: require('./components/radio-button'),
  RadioGroup: require('./components/radio-group'),
  Select: require('./components/select'),
  SelectablePill: require('./components/selectable-pill'),
  SelectablePillGroup: require('./components/selectable-pill-group'),
  Statistic: require('./components/statistic'),
  StyleChild: require('./components/style-child'),
  Table: require('./components/table'),
  Text: require('./components/text'),
  Textarea: require('./components/textarea')
}
